### ISSUE TITLE
Use of the property "instrument"

### ISSUE THREAD

**Issue by sfolsom** [LD4/entity_metadata_management#8]
I’m not sure the examples in the documentation are using the “instrument” property correctly after looking closer at the Activity Stream definition, https://www.w3.org/TR/activitystreams-vocabulary/#dfn-instrument. Instruments seem to be specific services/tools used during an activity, not an output/artifact of the activity. I wonder if might what to use rdf_patch “results” directly off the activity instead, e.g.

 
      "type": "Create",
      "object": "[http://example.org/](http://example.org/Milk)CowMilk",
      "result": {
    		"type": "rdf_patch",
    		"id": "https://data.my.authority/change_documents/2021/activity-stream/cd11/instrument/1",
		“content”: "A <https://my_repo/entity/cow_milk> 
         		<https://my.authority/vocab/hasLabel> 'cow milk'@en.
     			A <https://my_repo/entity/cow_milk> 
<https://my.authority/vocab/broaderTerm> <https://my_repo/entity/milk>.
     			A <https://my_repo/entity/cow_milk> 
         		<https://my.authority/vocab/narrow_term> 
        		 <https://my_repo/entity/bovine_milk>."
  }

Currently the nesting examples have Activities linking to Patches using "instrument", but Patch Instruments link to activities through "partOf". "partOf "has a Domain of CollectionPage. If we decide that the Patches should link back to the Activities (and decide to use "result" instead of "instrument") we could create a local property "resultOf" since the AS property "result" doesn’t have an established reciprocal property.

**Comment by zimeon** [comment]
I agree that `instrument` does't feel right according to the AS spec. I haven't found anything better that `result` yet but I'm not sure that feels quite right either

**Comment by zimeon** [comment]
For easy reference:
* [instrument](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-instrument) is defined as _"Identifies one or more objects used (or to be used) in the completion of an Activity."_
* [result](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-result) is defined as _"Describes the result of the activity. For instance, if a particular action results in the creation of a new resource, the result property can be used to describe that new resource."_

**Comment by sfolsom** [comment]
We might want to consider creating our own sub-property for attachment that makes clear the thing linking to is parseable message about a _delta_ or _change_ to the dataset. @eslao and @NancyJean, thoughts?

**Comment by eslao** [comment]
I agree that "instrument" seems to fit oddly: it implies that the provider is using the rdf patch in the process of their activity (creating a new entity, making a change, etc). If I understand correctly, the rdf patch is a by-product of an activity and it's being provided for the convenience of the consumer so that they don't need to derefence the object of the activity to implement the change on their end (right?).

Looking at the definition for "result", this seems not entirely unsuitable: the rdf patch is one result of the activity, but is it more indirect that what the property definition and example are going for?

The definition of "attachment" and the object's relationship with the activity seem deliberately loose, which seems appropriate here. If we were to use attachment, would we want to model it as an object or a link? Steven, what would using a subproperty get us?

**Comment by eslao** [comment]
(Tangentially: Would we want to use rdf_patch as the type? Would it be a subclass of "Object"? Or of "Document", which itself is a subclass of "Object"?)

**Comment by zimeon** [comment]
We agreed on a pattern for use of RDF patch with `instrument`:

```
"instrument":
  {
    "type": "rdf_patch",
    "id": "https://data.my.authority/change_documents/2021/activity-stream/cd11/instrument/1" <-- PATCH 
  }
```

but then we decided #100, #105 that we will not include RDF Patch in the initial specification version. Closing won't fix.
